name: Run Tests and Publish Package to NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Telegram.Bot.Mediator.slnx

    - name: Build Solution
      run: dotnet build Telegram.Bot.Mediator.slnx --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test Telegram.Bot.Mediator.slnx --configuration Release --no-build --verbosity normal

    - name: Pack Library
      run: |
        dotnet pack src/Telegram.Bot.Mediator.csproj \
          --configuration Release \
          --no-build \
          -o out \
          /p:PackageVersion=1.0.${{ github.run_number }}

    - name: Publish to NuGet.org
      run: |
        dotnet nuget push "out/*.nupkg" \
          --source "https://api.nuget.org/v3/index.json"